image: node:latest

stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deployment:
  stage: deploy
  script:
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh deploy@api.lestaubiere.com /var/www/lestaubiere/api/scripts/installProduction.sh
  only:
    - master
  environment:
    name: production
    url: https://api.lestaubiere.com
