version: '2'

services:
  lumen:
    container_name: lestaubiere_lumen
    build: images/lumen
    working_dir: /var/www/lumen
    volumes:
      - .:/var/www/lumen

  lumen_nginx:
    container_name: lestaubiere_lumen_nginx
    build: images/nginx
    volumes_from:
      - lumen
    volumes:
      - ./logs:/var/www/logs/lumen
    ports:
      - 80:80

  lumen_db:
    container_name: lestaubiere_lumen_db
    image: mariadb:latest
    environment:
      - "MYSQL_DATABASE=lestaubiere_lumen"
      - "MYSQL_USER=lestaubiere"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    ports: 
      - "3306:3306"
